### ISSUE TITLE
lets revive this project

### ISSUE THREAD

**Issue by CheyenneForbes** [quasarframework/quasar-wrapper-express#1]
I'd like to revive this project

**Comment by smolinari** [comment]
@CheyenneForbes - That would be great, but the concept of wrappers has been dropped. The way to go now is with "app extensions", which just came out in v1.0.  We should be coming out with docs on how to develop an app extension soon, or you can look at the official ones for inspiration. 😄 

https://github.com/quasarframework/app-extension-dotenv
https://github.com/quasarframework/app-extension-icon-factory
https://github.com/quasarframework/app-extension-qmediaplayer
https://github.com/quasarframework/app-extension-feathersjs
https://github.com/quasarframework/quasar-testing

The last two are most interesting, as the feathersjs one is an API (which is in work too) and the quasar-testing one is the most advanced and working. 

Scott
